# .github/workflows/deploy.yml
name: Deploy App to GitHub Pages

on:
  push:
    branches:
      - main # mainブランチにプッシュされたときに実行

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # Vite プロジェクトをビルド
      - name: Build project
        run: npm run build

      # gh-pages ブランチにビルドされたファイルをデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
